# -*- coding: utf-8 -*-
E = {
 "Controlling robots via language": "通过语言控制机器人",
 "has a long history, including early demonstrations of human-robot interaction through lexical parsing of natural language ⟦0⟧. Language serves not only as an interface for non-experts to interact with robots ⟦1⟧, ⟦2⟧, but also as a means to compositionally scale generalization to new tasks ⟦3⟧, ⟦4⟧. The literature is vast (we refer to Tellex et al. ⟦5⟧ and Luketina et al. ⟦6⟧ for comprehensive surveys), but recent works fall broadly into the categories of high-level interpretation (e.g., semantic parsing ⟦7⟧, ⟦8⟧–⟦9⟧), planning ⟦10⟧, ⟦11⟧, ⟦12⟧, and low-level policies (e.g., model-based ⟦13⟧–⟦14⟧, imitation learning ⟦15⟧, ⟦16⟧, ⟦17⟧, ⟦18⟧, or reinforcement learning ⟦19⟧–⟦20⟧). In contrast, our work focuses on the code generation aspect of LLMs and use the generated procedures as an expressive way to control the robot.": "由来已久，早期就有通过对自然语言进行词法解析实现人机交互的演示 ⟦0⟧。语言不仅是非专业人员与机器人交互的界面 ⟦1⟧、⟦2⟧，也是把泛化能力组合式地扩展到新任务的手段 ⟦3⟧、⟦4⟧。相关文献浩繁（综述可参见 Tellex 等 ⟦5⟧ 与 Luketina 等 ⟦6⟧），但近期工作大致可分为高层解释（如语义解析 ⟦7⟧、⟦8⟧–⟦9⟧）、规划 ⟦10⟧、⟦11⟧、⟦12⟧，以及底层策略（如基于模型的方法 ⟦13⟧–⟦14⟧、模仿学习 ⟦15⟧、⟦16⟧、⟦17⟧、⟦18⟧，或强化学习 ⟦19⟧–⟦20⟧）几类。与之相比，我们的工作聚焦于 LLM 的代码生成能力，并把生成的程序作为控制机器人的一种富有表达力的方式。",
 "Large language models": "大语言模型",
 "exhibit impressive zero-shot reasoning capabilities: from planning ⟦0⟧ to writing math programs ⟦1⟧; from solving science problems ⟦2⟧ to using trained verifiers ⟦3⟧ for math word problems. These can be improved with prompting methods such as Least-to-Most ⟦4⟧, Think-Step-by-Step ⟦5⟧ or Chain-of-Thought ⟦6⟧. Most closely related to this paper are works that use LLM capabilities for robot agents without additional model training. For example, Huang et al. decompose natural language commands into sequences of executable actions by text completion and semantic translation ⟦7⟧, while SayCan ⟦8⟧ generates feasible plans for robots by jointly decoding an LLM weighted by skill affordances ⟦9⟧ from value functions. Inner Monologue ⟦10⟧ expands LLM planning by incorporating outputs from success detectors or other visual language models and uses their feedback to re-plan. Socratic Models ⟦11⟧ uses visual language models to substitute perceptual information (in teal) into the language prompts that generate plans, and it uses language-conditioned policies e.g., for grasping ⟦12⟧. The following example illustrates the qualitative differences between our approach versus the aforementioned prior works. When tasked to \"move the coke can a bit to the right\":": "展现出令人印象深刻的零样本推理能力：从规划 ⟦0⟧ 到编写数学程序 ⟦1⟧；从解答科学问题 ⟦2⟧ 到用训练好的验证器 ⟦3⟧ 解决数学应用题。这些能力还可以通过 Least-to-Most ⟦4⟧、Think-Step-by-Step ⟦5⟧ 或 Chain-of-Thought ⟦6⟧ 等提示方法进一步提升。与本文最相关的是那些无需额外训练即把 LLM 能力用于机器人智能体的工作。例如，Huang 等人通过文本补全与语义翻译把自然语言指令分解为可执行动作序列 ⟦7⟧；SayCan ⟦8⟧ 则通过联合解码 LLM 并以来自价值函数的技能可行性 ⟦9⟧ 加权，为机器人生成可行计划。Inner Monologue ⟦10⟧ 把成功检测器或其他视觉语言模型的输出纳入 LLM 规划，并利用其反馈重新规划。Socratic Models ⟦11⟧ 用视觉语言模型把感知信息（青色）替换进生成计划的语言提示，并使用语言条件策略，例如用于抓取 ⟦12⟧。下面的例子说明了我们的方法与上述先前工作的定性差异。当任务是“把可乐罐往右移一点”时：",
 "2. Examples": "2. 示例（Examples）",
 "are instruction-to-code pairs that present few-shot \"demonstrations\" of how natural language instructions should be converted into code. These may include performing arithmetic, calling other APIs, and other features of the programming language. Instructions are written as comments directly preceding a block of corresponding solution code. We can maintain an LMP \"session\" by incrementally appending new instructions and responses to the prompt, allowing later instructions to refer back to previous instructions, like \"undo the last action\".": "即指令到代码的配对，以少样本“演示”展示自然语言指令应如何转换为代码。这些示例可以包括算术运算、调用其他 API 以及编程语言的其他特性。指令写成注释，直接置于对应解答代码块之前。我们可以通过把新的指令与响应逐步追加到提示词中来维持一个 LMP“会话”，使后续指令能够回指先前指令，例如“撤销上一个动作”。",
 "LMPs can be composed": "LMP 可以",
 "via nested function calls. This allows including more few-shot examples into individual prompts to improve functional accuracy and scope, while remaining within the LLM’s maximum input token length. The following (full prompt in B.4) generates a response that uses ⟦0⟧ another LMP that associates object names with language descriptions:": "通过嵌套函数调用进行组合。这使得每个提示词可以容纳更多少样本示例以提升功能准确性与覆盖范围，同时不超过 LLM 的最大输入 token 长度。下面的例子（完整提示词见 B.4）生成的响应使用了 ⟦0⟧，这是另一个把物体名称与语言描述关联起来的 LMP：",
 "RoboCodeGen:": "RoboCodeGen：",
 "we introduce a new benchmark with 37 function generation problems with several key differences from previous code-gen benchmarks: (i) it is robotics-themed with questions on spatial reasoning (e.g., find the closest point to a set of points), geometric reasoning (e.g., check if one bounding box is contained in another), and controls (e.g., PD control), (ii) using third-party libraries (e.g. NumPy) are both allowed and encouraged, (iii) provided function headers have no docstrings nor explicit type hints, so LLMs need to infer and use common conventions, and (iv) using not-yet-defined functions are also allowed, which can be created with hierarchical code-gen. Example benchmark questions can be found in Appendix E. We evaluate on four LLMs accessible from the OpenAI API⟦0⟧. As with standard benchmarks ⟦1⟧, our evaluation metric is the percentage of the generated code that passes human-written unit tests. See Table I. Domain-specific language models (Codex model) generally perform better. Within each model family, performance improves with larger models. Hierarchical performs better across the board, showing the benefit of allowing the LLM to break down complex functions into hierarchical parts and generate code for each part separately. We also analyze how code generation performance varies across the five types of generalization proposed in ⟦2⟧. Hierarchical helps Productivity the most, which is when the new instruction requires longer code, or code with more logic layers than those in Examples. These improvements however, only occur with the two davinci models, and not cushman, suggesting that a certain level of code-generation capability needs to be reached first before hierarchical code-gen can bring further improvements. More results are in Appendix E.2. Evaluations in HumanEval ⟦3⟧ demonstrate that hierarchical code-gen improves not only policy code, but also general-purpose code. See Table II. Numbers achieved are higher than in recent works ⟦4⟧, ⟦5⟧, ⟦6⟧. More details in Appendix D.": "我们提出一个包含 37 个函数生成问题的新基准，它与以往代码生成基准有几个关键区别：（i）以机器人为主题，问题涉及空间推理（例如找到离一组点最近的点）、几何推理（例如判断一个包围盒是否包含在另一个之中）和控制（例如 PD 控制）；（ii）允许并鼓励使用第三方库（如 NumPy）；（iii）给出的函数头没有文档字符串也没有显式类型提示，因此 LLM 需要推断并使用常见约定；（iv）允许使用尚未定义的函数，这些函数可通过分层代码生成创建。基准问题示例见附录 E。我们在 OpenAI API 可访问的四个 LLM 上进行评估⟦0⟧。与标准基准 ⟦1⟧ 一样，评估指标是生成代码通过人工编写单元测试的百分比。见表 I。领域专用语言模型（Codex 模型）总体表现更好。在同一模型家族内，模型越大性能越好。分层方法全面领先，表明让 LLM 把复杂函数分解为层次化部分并分别生成代码是有益的。我们还分析了代码生成性能在 ⟦2⟧ 提出的五种泛化类型上的差异。分层方法对 Productivity（生产性）帮助最大，即新指令需要比 Examples 更长的代码或更多逻辑层次的情形。不过这些提升只出现在两个 davinci 模型上，cushman 上没有，说明需要先达到一定的代码生成能力，分层代码生成才能带来进一步提升。更多结果见附录 E.2。在 HumanEval ⟦3⟧ 上的评估表明，分层代码生成不仅改善策略代码，也改善通用代码。见表 II。所取得的数字高于近期工作 ⟦4⟧、⟦5⟧、⟦6⟧。更多细节见附录 D。"
}
