# -*- coding: utf-8 -*-
# translations keyed by the exact source text of blocks that the translate pipeline segments differently from `export`
E = {}
E["Fig. 2: Code as Policies can follow natural language instructions across diverse domains and robots: table-top manipulation (a)-(b), 2D shape drawing (c), and mobile manipulation in a kitchen with robots from Everyday Robots (d). Our approach enables robots to perform spatial-geometric reasoning, parse object relationships, and form multi-step behaviors using off-the-shelf models and few-shot prompting with no additional training. See full videos and more tasks at code-as-policies.github.io We present Code as Policies (CaP): a robot-centric formulation of language model generated programs (LMPs) executed on real systems. Pythonic LMPs can express complex policies using:"] = "图 2：Code as Policies 能够在多种领域和机器人上遵循自然语言指令：桌面操作 (a)-(b)、二维图形绘制 (c)，以及使用 Everyday Robots 机器人在厨房中进行移动操作 (d)。我们的方法让机器人无需额外训练，仅用现成模型和少样本提示就能进行空间几何推理、解析物体关系并形成多步行为。完整视频与更多任务见 code-as-policies.github.io。我们提出 Code as Policies（CaP）：一种在真实系统上执行的、以机器人为中心的语言模型生成程序（LMP）表述方式。Python 风格的 LMP 可以用以下手段表达复杂策略："
E["⟦0⟧ Classic logic structures e.g., sequences, selection (if/else), and loops (for/while) to assemble new behaviors at runtime. ⟦1⟧ Third-party libraries to interpolate points (NumPy), analyze and generate shapes (Shapely) for spatial-geometric reasoning, etc."] = "⟦0⟧ 经典逻辑结构，例如顺序、选择（if/else）和循环（for/while），在运行时组装新行为。⟦1⟧ 第三方库，例如用 NumPy 插值点、用 Shapely 分析与生成形状以进行空间几何推理等。"
E["Third-party libraries."] = "第三方库。"
E["Python code-writing LLMs store knowledge of many popular libraries. LMPs can be prompted to use these libraries to perform complex instructions without writing all of the code e.g., using NumPy to elicit spatial reasoning with coordinates. Hints here include import statements, and Examples define cardinal directions. Variable names are also important to indicate that ⟦1⟧ and⟦0⟧ are NumPy arrays. Operations with 2D vectors imply that the points are also 2D. Example:"] = "会写 Python 代码的 LLM 存储着许多流行库的知识。可以提示 LMP 使用这些库来执行复杂指令，而无需把所有代码都写出来，例如用 NumPy 进行基于坐标的空间推理。此处 Hints 包含 import 语句，Examples 定义了基本方位。变量名同样重要，用于表明 ⟦1⟧ 和⟦0⟧ 是 NumPy 数组。对二维向量的运算意味着这些点也是二维的。示例："
E["First-party libraries."] = "第一方库。"
E["LMPs can also use first-party libraries (perception or control primitive APIs) not found in the training data if those functions have meaningful names and are provided in Hints/Examples. For example (full prompt in B.2):"] = "如果函数名有意义并在 Hints/Examples 中给出，LMP 也可以使用训练数据中不存在的第一方库（感知或控制原语 API）。例如（完整提示词见 B.2）："
E["Control flows."] = "控制流。"
E["Programming languages allow using control structures such as if-else and loop statements. Previously we showed LMPs can express for-loops in the form of list comprehensions. Here we show how they can write a while-loop can form a simple feedback policy. Note that the prompt (same as the one in B.2) does not contain such Examples:"] = "编程语言允许使用 if-else 和循环语句等控制结构。前面我们展示了 LMP 能以列表推导的形式表达 for 循环。这里我们展示它们如何写出 while 循环，从而构成一个简单的反馈策略。注意提示词（与 B.2 相同）中并不包含此类 Examples："
E["function generation."] = "函数生成。"
E["The following example shows how LMPs can combine these capabilities to follow more complex instructions and perform a task in the tabletop manipulation domain. Prompts are omitted for brevity, but they are similar to previous ones. The high-level LMP generates high-level policy behavior and relies on ⟦0⟧ to get object names by language descriptions:"] = "下面的例子展示 LMP 如何组合这些能力来遵循更复杂的指令并完成桌面操作领域的任务。为简洁起见省略了提示词，但它们与前面的类似。高层 LMP 生成高层策略行为，并依靠 ⟦0⟧ 根据语言描述获取物体名称："
